#!/usr/bin/env bash
set -Eeuo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

echo "Checking for build tools ..."
command -v direnv &>/dev/null || brew install direnv
command -v pod    &>/dev/null || brew install cocoapods

echo "Setup complete in $SECONDS seconds"
