#!/usr/bin/env bash
SECONDS=0
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

echo "Checking for build tools ..."
command -v direnv &>/dev/null || brew install direnv
command -v pod    &>/dev/null || brew install cocoapods

install-git-hooks

echo "Setup complete in $SECONDS seconds"
